version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
  - copyloopvar
  - dupl
  - errcheck
  - ginkgolinter
  - goconst
  - gocyclo
  - govet
  - ineffassign
  - misspell
  - nakedret
  - prealloc
  - revive
  - staticcheck
  - unconvert
  - unparam
  - unused
  exclusions:
    generated: lax
    paths:
      - .*_test\.go
  # Ref: https://golangci-lint.run/docs/linters/configuration
  settings:
    cyclop:
      max-complexity: 18 # maximal code complexity to report; default 10
      package-average: 16.0 # maximal average package complexity to report; default 0.0
    gocognit:
      min-complexity: 30 # minimal code complexity to report; default: 30
    govet:
      enable-all: true
      disable:
        - fieldalignment # too strict
        - shadow # too strict
formatters:
  enable:
  - gofmt
  - goimports