name: GoVulnCheck

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: govulncheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck-pr-scan:
    runs-on: ubuntu-latest
    container:
      image: golang:1.26.7-alpine3.23@sha256:b17af760035fc2f338eed92d448a6c67f2d45438844fc6c60678fa5f99e44b57
    steps:
      - name: install-govulncheck
        run: GOBIN=/usr/local/bin go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: govulncheck-scan
        run: |
          go version
          govulncheck -mode source ./...
