name: GoVulnCheck

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: govulncheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck-pr-scan:
    runs-on: ubuntu-latest
    container:
      image: golang:1.26.3-alpine3.22@sha256:be93003ee861b3b91b6ebcb22678524947e0cd786c2df3f32af520006b1e54f5
    steps:
      - name: install-govulncheck
        run: GOBIN=/usr/local/bin go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: govulncheck-scan
        run: |
          go version
          govulncheck -mode source ./...
