on:
  push:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          cache: false
          go-version-file: go.mod

      - name: Test
        run: make test

      - name: Workaround for https://github.com/codecov/feedback/issues/263
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
        with:
          file: ./cover.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
